[workspace]
resolver = "2"

members = [
    "19.1.Unsafe",
    "19.2.AdvancedTraits",
    "19.3.AdvancedTypes",
    "19.4.AdvancedFunctions",
    "19.5.Macros",
    "advanced_macros",
    "advanced_macros/advanced_macros_derived",
]
